source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'git@gitlab.miliantech.com:miliantech-ios/Specs.git'

platform :ios, '10.0'

use_modular_headers!
inhibit_all_warnings!

target 'YDTCUIKitExamlple' do
  pod 'YDTCUIKit', :path => '../YDTCUIKit.podspec'
  #pod 'YDAccountService', :path => '../../YDAccountService'
  
 
end
